user_login_register:
    path:     /
    defaults: { _controller: IDUserBundle:Default:loginAndRegister }

cas_connect:
    path:     /cas
    defaults: { _controller: IDUserBundle:Default:CAS }

cas_force:
    path:     /force
    defaults: { _controller: IDUserBundle:Default:force }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

